load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")

load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")
load("@mgk_info//:kernel_version.bzl","kernel_version",)


package(
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "public_headers",
    srcs = ["isp8/cam/mtk_cam-bwr.h"],
)

mgk_camsys_outs = [
    # keep sorted
    "isp7_1/cam/mtk-cam-isp.ko",
    "isp7s/cam_legacy/mtk-cam-isp7s.ko",
    "isp7sp/cam/mtk-cam-isp7sp.ko",
    "isp8/cam/mtk-cam-isp8.ko",
    "isp8s/cam/mtk-cam-isp8s.ko",
]

define_mgk_ko(
    name = "camsys",
    srcs = glob([
        "**/*.c",
        "**/*.h",
        "**/Kbuild",
        "**/Makefile",
    ]) + [
        "//vendor/mediatek/kernel_modules/mtkcam:public_headers",
        "//vendor/mediatek/kernel_modules/mtkcam/imgsensor:public_headers",
        "//vendor/mediatek/kernel_modules/mtkcam:kbuild_makefiles",
    ],
    deps = [
        "//vendor/mediatek/kernel_modules/mtkcam/imgsensor:mtk_imgsensor",
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk-cam-plat-util",
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:ccd_rpmsg",
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk_ccd_remoteproc"] +
        (["//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk-cam-plat-mt6983"] if glob(["isp7_1/cam/mtk_cam-plat-mt6983.c"]) else []) +
        (["//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk-cam-plat-mt6879"] if glob(["isp7_1/cam/mtk_cam-plat-mt6879.c"]) else []) +
        (["//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk-cam-plat-mt6895"] if glob(["isp7_1/cam/mtk_cam-plat-mt6895.c"]) else []),
    outs = mgk_camsys_outs,
)

define_mgk_ddk_ko(
    name = "ccd_rpmsg",
    srcs = [
        "rpmsg/mtk_ccd_rpmsg.c",
        "rpmsg/mtk_ccd_rpmsg_ipi.c",
        "rpmsg/mtk_ccd_rpmsg_client.c",
    ] + glob(["**/*.h"]),
    copts = [
        "-I$(srctree)/drivers/rpmsg",
    ],
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
    ],
)

define_mgk_ddk_ko(
    name = "mtk_ccd_remoteproc",
    srcs = [
        "remoteproc/mtk_ccd.c",
        "remoteproc/mtk_ccd_mem.c",
    ] + glob(["**/*.h"]),
    copts = [
        "-I$(srctree)/drivers/remoteproc",
    ],
    ko_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:ccd_rpmsg",
        "//kernel_device_modules-{}/drivers/misc/mediatek/iommu:mtk_iommu_util".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/iommu:iommu_debug".format(kernel_version),
    ],
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
        "//kernel_device_modules-{}/drivers/misc/mediatek/iommu:iommu_misc_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/iommu/arm/arm-smmu-v3:smmu_public_headers".format(kernel_version),
    ],
)

define_mgk_ddk_ko(
    name = "mtk-cam-plat-util",
    srcs = [
        "isp7_1/cam/mtk_cam-plat-util.c",
    ] + glob([
        "common/mtk_cam-fmt.h",
        "isp7_1/cam/*.h",
    ]),
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
    ],
)

define_mgk_ddk_ko(
    name = "mtk-cam-plat-mt6983",
    srcs = [
        "isp7_1/cam/mtk_cam-plat-mt6983.c",
    ] + glob([
        "common/mtk_cam-fmt.h",
        "isp7_1/cam/*.h",
    ]),
    ko_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk-cam-plat-util",
    ],
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
        "//vendor/mediatek/kernel_modules/mtkcam/imgsensor:imgsensor_header",
    ],
    local_defines = ["CAMSYS_MRAW_V1"],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/imgsensor",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/imgsensor/inc",
    ],
)

define_mgk_ddk_ko(
    name = "mtk-cam-plat-mt6879",
    srcs = [
        "isp7_1/cam/mtk_cam-plat-mt6879.c",
    ] + glob([
        "common/mtk_cam-fmt.h",
        "isp7_1/cam/*.h",
    ]),
    ko_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk-cam-plat-util",
    ],
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
        "//vendor/mediatek/kernel_modules/mtkcam/imgsensor:imgsensor_header",
    ],
    local_defines = ["DCAMSYS_MRAW_V2"],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/imgsensor",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/imgsensor/inc",
    ],
)

define_mgk_ddk_ko(
    name = "mtk-cam-plat-mt6895",
    srcs = [
        "isp7_1/cam/mtk_cam-plat-mt6895.c",
    ] + glob([
        "common/mtk_cam-fmt.h",
        "isp7_1/cam/*.h",
    ]),
    ko_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk-cam-plat-util",
    ],
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
        "//vendor/mediatek/kernel_modules/mtkcam/imgsensor:imgsensor_header",
    ],
    local_defines = ["CAMSYS_MRAW_V3"],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/imgsensor",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/imgsensor/inc",
    ],
)

define_mgk_ddk_ko(
    name = "cam-isp7_1-ut",
    srcs = [
        "isp7_1/unit_test/mtk_cam_ut-cam.c",
        "isp7_1/unit_test/mtk_cam_ut-camsv.c",
        "isp7_1/unit_test/mtk_cam_ut-seninf.c",
        "isp7_1/unit_test/mtk_cam_ut.c",
    ] + glob([
        "common/mtk_cam-fmt.h",
        "isp7_1/unit_test/*.h",
        "isp7_1/cam/mtk_cam-ipi.h",
        "isp7_1/cam/mtk_cam-defs.h",
        "isp7_1/cam/mtk_cam-sv-regs.h",
    ]),
    ko_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:ccd_rpmsg",
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk_ccd_remoteproc",
    ],
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
    ],
)

define_mgk_ddk_ko(
    name = "cam-isp7s-ut",
    srcs = [
        "isp7s/unit_test/mtk_cam_ut-cam.c",
        "isp7s/unit_test/mtk_cam_ut-camsv.c",
        "isp7s/unit_test/mtk_cam_ut-seninf.c",
        "isp7s/unit_test/mtk_cam_ut.c",
    ] + glob([
        "common/mtk_cam-fmt.h",
        "isp7s/unit_test/*.h",
        "isp7s/cam_legacy/mtk_cam-ipi.h",
        "isp7s/cam_legacy/mtk_cam-defs.h",
        "isp7_1/cam/mtk_cam-sv-regs.h",
    ]),
    ko_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:ccd_rpmsg",
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk_ccd_remoteproc",
    ],
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
    ],
)

define_mgk_ddk_ko(
    name = "cam-isp7sp-ut",
    srcs = [
        "isp7sp/unit_test/mtk_cam_ut-cam.c",
        "isp7sp/unit_test/mtk_cam_ut-camsv.c",
        "isp7sp/unit_test/mtk_cam_ut-mraw.c",
        "isp7sp/unit_test/mtk_cam_ut-seninf.c",
        "isp7sp/unit_test/mtk_cam_ut.c",
    ] + glob([
        "common/mtk_cam-fmt.h",
        "isp7sp/unit_test/*.h",
        "isp7sp/cam/mtk_cam-ipi.h",
        "isp7sp/cam/mtk_cam-defs.h",
        "isp7sp/cam/mtk_cam-sv-regs.h",
        "isp7sp/cam/mtk_cam-mraw-regs.h",
    ]),
    ko_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:ccd_rpmsg",
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk_ccd_remoteproc",
    ],
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
    ],
)

define_mgk_ddk_ko(
    name = "cam-isp8-ut",
    srcs = [
        "isp8/unit_test/mtk_cam_ut-cam.c",
        "isp8/unit_test/mtk_cam_ut-camsv.c",
        "isp8/unit_test/mtk_cam_ut-mraw.c",
        "isp8/unit_test/mtk_cam_ut-seninf.c",
        "isp8/unit_test/mtk_cam_ut.c",
    ] + glob([
        "common/mtk_cam-fmt.h",
        "isp8/unit_test/*.h",
        "isp8/cam/mtk_cam-ipi.h",
        "isp8/cam/mtk_cam-defs.h",
        "isp8/cam/mtk_cam-sv-regs.h",
        "isp8/cam/mtk_cam-mraw-regs.h",
    ]),
    ko_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:ccd_rpmsg",
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk_ccd_remoteproc",
    ],
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
    ],
)

define_mgk_ddk_ko(
    name = "cam-isp8s-ut",
    srcs = [
        "isp8s/unit_test/mtk_cam_ut-cam.c",
        "isp8s/unit_test/mtk_cam_ut-camsv.c",
        "isp8s/unit_test/mtk_cam_ut-seninf.c",
        "isp8s/unit_test/mtk_cam_ut.c",
    ] + glob([
        "common/mtk_cam-fmt.h",
        "isp8s/unit_test/*.h",
        "isp8s/cam/mtk_cam-ipi.h",
        "isp8s/cam/mtk_cam-defs.h",
        "isp8s/cam/mtk_cam-sv-regs.h",
    ]),
    ko_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:ccd_rpmsg",
        "//vendor/mediatek/kernel_modules/mtkcam/camsys:mtk_ccd_remoteproc",
    ],
    header_deps = [
        "//vendor/mediatek/kernel_modules/mtkcam:mtkcam_header",
    ],
)
