# SPDX-License-Identifier: GPL-2.0-only

KO_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

ccflags-y += \
        -I$(DEVICE_MODULES_PATH)/drivers/rpmsg/ \
        -I$(DEVICE_MODULES_PATH)/drivers/remoteproc/ \
        -I$(DEVICE_MODULES_PATH)/include/ \
        -I$(KO_PATH)/../../ccd_client

cam-isp8-ut-objs := \
        mtk_cam_ut-cam.o \
        mtk_cam_ut-seninf.o \
        mtk_cam_ut.o \
        mtk_cam_ut-camsv.o \
        mtk_cam_ut-mraw.o \
        ../../ccd_client/mtk_ccd_client.o

obj-$(CONFIG_VIDEO_MTK_ISP_CAMSYS) += cam-isp8-ut.o
